GET http://localhost:8082/status
Authorization: LetMeIn
###
GET http://localhost:8082
Authorization: LetMeIn
###
GET http://localhost:8082/currencies
# Authorization: LetMeIn
###
GET http://localhost:8082/currencies?min_value=0.01
Authorization: LetMeIn
###
GET http://localhost:8082/currencies/gbp
# Authorization: LetMeIn
###
GET http://localhost:8082/users
Authorization: LetMeIn

###
GET http://localhost:8082/users/6607d086-7159-4c26-beb1-280c9f9cbf35
Authorization: LetMeIn
###
GET http://localhost:8082/users/search?age=49&gender=male
Authorization: LetMeIn
###
GET http://localhost:8082/blogs
###
GET http://localhost:8082/blogs/664cd118685b621b7a6f151f
###
POST http://localhost:8082/blogs
Authorization: LetMeIn
Content-Type: application/json

{
  "title": "India Elections",
  "author": [
    {
      "fullName": "Rubbish Kr",
      "email": "rubbish@ndtv.in",
      "twitterHandle": "@_rubbish_aap",
      "image": "https://pbs.twimg.com/profile_images/3767286347"
    }
  ],
  "content": "Last 2 phases left"
}

###
DELETE http://localhost:8082/blogs/664cd118685b621b7a6f151f
Authorization: LetMeIn

###
PATCH http://localhost:8082/blogs/664cc5de17f21b0e9fa02b22
Authorization: LetMeIn
Content-Type: application/json

{
  "content": "Elections coming up"
}

###
GET http://localhost:8082/blogs/search?title=Australia%20Elections&author=john@abc.in

###
GET http://localhost:8082/blogs/search?author=john@abc.in

###
GET http://localhost:8082/blogs/search?title=elections