GET http://localhost:8082/status

###
GET http://localhost:8082

###
GET http://localhost:8082/currencies

###
GET http://localhost:8082/currencies?min_value=0.01

###
GET http://localhost:8082/currencies/inr